import LegalLayout, { Section } from './LegalLayout.jsx'
import { CONTACT_EMAIL } from '../lib/constants.js'

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" updated="July 15, 2026">
      <Section heading="1. Agreement to Terms">
        <p>
          These Terms of Service (“Terms”) govern your access to and use of the services
          provided by LeadSavior AI (“LeadSavior,” “we,” “us,” or “our”), including our AI
          Receptionist, Review Poacher, and Website Builder products, our website, and any
          related services (collectively, the “Services”). By purchasing, accessing, or using
          the Services, you agree to be bound by these Terms. If you are using the Services on
          behalf of a business, you represent that you have authority to bind that business to
          these Terms.
        </p>
      </Section>

      <Section heading="2. The Services">
        <p>
          LeadSavior provides AI-powered growth tools for local service businesses, including:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            <strong className="text-white/90">AI Receptionist</strong> — automated call
            answering, appointment booking, FAQ handling, follow-up messaging, and a website
            chat widget.
          </li>
          <li>
            <strong className="text-white/90">Review Poacher</strong> — monitoring of publicly
            available competitor reviews with alerts and suggested outreach messaging.
          </li>
          <li>
            <strong className="text-white/90">Website Builder</strong> — design, build, and
            maintenance of a custom business website.
          </li>
        </ul>
        <p>
          Specific features included with your subscription depend on the plan you purchase.
          Final pricing is confirmed during onboarding and may be adjusted based on project
          scope before you are billed.
        </p>
      </Section>

      <Section heading="3. Subscriptions, Billing, and Cancellation">
        <p>
          All plans are billed monthly, in advance, on a month-to-month basis. There are no
          long-term contracts. Your subscription renews automatically each month until
          cancelled.
        </p>
        <p>
          You may cancel at any time with no cancellation fee by emailing{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-teal hover:text-neon">{CONTACT_EMAIL}</a>.
          Cancellation takes effect at the end of your current billing period, and you retain
          access to the Services until then. See our{' '}
          <a href="/refunds" className="text-teal hover:text-neon">Refund &amp; Cancellation Policy</a>{' '}
          for details.
        </p>
        <p>
          If a payment fails, we may suspend the Services until payment is resolved. Prices
          may change with at least 30 days’ notice; changes apply from your next billing
          period.
        </p>
      </Section>

      <Section heading="4. Onboarding and Client Responsibilities">
        <p>
          Setup of the Services requires information from you, such as details about your
          business, services, pricing, calendars, and phone systems. You agree to provide
          accurate information and reasonable cooperation during onboarding. Timelines we
          communicate (such as 48-hour setup) begin once we have the information and access we
          need from you.
        </p>
        <p>
          You are responsible for the accuracy of information the Services communicate on your
          behalf (for example, your pricing and service descriptions) and for reviewing leads,
          messages, and appointments generated by the Services.
        </p>
      </Section>

      <Section heading="5. Acceptable Use">
        <p>You agree not to use the Services to:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>violate any applicable law or regulation, including telemarketing, text-messaging (TCPA), and anti-spam laws;</li>
          <li>send harassing, deceptive, or unsolicited communications;</li>
          <li>misrepresent your identity or business;</li>
          <li>infringe the rights of any third party; or</li>
          <li>reverse engineer, resell, or misuse the Services or underlying technology.</li>
        </ul>
        <p>
          Outreach to prospective customers using information surfaced by the Services is
          initiated by you, and you are responsible for ensuring your outreach complies with
          applicable laws in your jurisdiction.
        </p>
      </Section>

      <Section heading="6. Intellectual Property">
        <p>
          We retain all rights in the Services, our technology, and our branding. Content you
          provide to us (your logos, business information, photos) remains yours, and you
          grant us a license to use it to provide the Services. Websites we build for you are
          licensed to you for the duration of your subscription; custom content we create for
          your website (copy, page designs) may be exported by you if your subscription ends.
        </p>
      </Section>

      <Section heading="7. Disclaimers">
        <p>
          The Services are provided “as is” and “as available.” While we work hard to deliver
          great results, we do not guarantee any specific business outcome, including call
          volumes, lead counts, search rankings, revenue, or conversion rates. Examples and
          testimonials on our website reflect individual experiences and are not promises of
          similar results.
        </p>
        <p>
          AI-generated responses may occasionally be inaccurate. We disclaim all warranties,
          express or implied, including merchantability, fitness for a particular purpose, and
          non-infringement, to the maximum extent permitted by law.
        </p>
      </Section>

      <Section heading="8. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, LeadSavior will not be liable for indirect,
          incidental, special, consequential, or punitive damages, or for lost profits or lost
          business, arising from or related to the Services. Our total liability for any claim
          will not exceed the amounts you paid us in the three (3) months preceding the event
          giving rise to the claim.
        </p>
      </Section>

      <Section heading="9. Termination">
        <p>
          You may terminate by cancelling your subscription at any time. We may suspend or
          terminate the Services for breach of these Terms, unlawful use, or non-payment. On
          termination, your access to the Services ends at the close of the paid billing
          period.
        </p>
      </Section>

      <Section heading="10. Changes to These Terms">
        <p>
          We may update these Terms from time to time. Material changes will be communicated
          by email or a notice on our website, and continued use of the Services after changes
          take effect constitutes acceptance.
        </p>
      </Section>

      <Section heading="11. Governing Law">
        <p>
          These Terms are governed by the laws of the State of Florida, USA, without regard to
          conflict-of-law principles. Any disputes will be resolved in the state or federal
          courts located in Florida.
        </p>
      </Section>

      <Section heading="12. Contact">
        <p>
          Questions about these Terms? Contact us at{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-teal hover:text-neon">{CONTACT_EMAIL}</a>.
        </p>
      </Section>
    </LegalLayout>
  )
}
